image:
  file: .gitpod.Dockerfile

ports:
    - port: 3000
      onOpen: open-preview
      
tasks:
    - init: pip3 install -r requirements.txt
      command: python3 app.py

github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: false
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false